### ISSUE TITLE
А что если добавить возможность изменять view для писем?

### ISSUE THREAD

**Issue by mazurva** [pistol88/yii2-order#10]
Есть проблема, по каким то причинам при отправке письма поля 3 раза повторяются. Кроме того, хочется кроме наименования товара видеть его артикул(или id) и фото.
Может добавить параметр viewMail? Или применять стандартный механизм темизации?

**Comment by pistol88** [comment]
Какие поля 3 раза повторяются?
Если нужно кастомное письмо, лучше привязаться к событию 'on create' в конфиге и отсылать свое собственное письмо.

**Comment by mazurva** [comment]
Повторяются динамические поля.
Если сделать свое письмо, то админу будет приходить 2 письма, может появиться путаница.

**Comment by mazurva** [comment]
Вообщем пока нашел вариант через mailer подменять письма:
```php
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'view' => [
                'theme' => [
                    'pathMap' => [
                        '@vendor/pistol88/yii2-order/mails' => '@frontend/views/order/mails',
                    ],
                ],
            ],
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => '', // введите хост или ip почтового сервера
                'username' => '', // введите логин
                'password' => '', // введите пароль
                'port' => '465',    // порт назначается в зависимости от службы
                'encryption' => 'ssl',
             ],
        ],
```
Но для этого на всякий случай в Module.php желательно прописать (хотя сейчас и так работает):
```php
// $this->mail->viewPath = __DIR__ . '/mails';
$this->mail->viewPath = '@vendor/pistol88/yii2-order/mails';
```
С дублями еще не разобрался, но выяснил что 3 раза данные записываются в таблицу `order_field_value`.
