### ISSUE TITLE
А где можно посмотреть оплаченные товары?

### ISSUE THREAD

**Issue by mazurva** [pistol88/yii2-order#11]
В разделе "Заказы" не видно оплачен товар или нет. В карточки заказа, тоже самое. Т.е. если товар уже оплачен, то как минимум тут этого не видно.

**Comment by mazurva** [comment]
При необходимости могу скинуть несколько "Pull requests" на эту тему.

**Comment by pistol88** [comment]
По идее, это поле можно заинжектить в конфиге модуля:
` 'orderColumns' => ['client_name', 'phone', 'email', 'payment_type_id', 'shipping_type_id', 'payment'];`

**Comment by mazurva** [comment]
А с фильтрацией тогда не очень будет. Т.е. если нужно отфильтровать только оплаченные заказы.

**Comment by pistol88** [comment]
Тогда да, можно пулл реквест. Только с настройкой showPaymentColumn в модуле с положением false пол умолчанию.

**Comment by mazurva** [comment]
Хорошо. Работаю
