### ISSUE TITLE
Вываливается в ошибку по интерфейсу, поправка к README

### ISSUE THREAD

**Issue by TheElk** [pistol88/yii2-order#19]
Расширение гуд, но про класс Filling не хватает в ридми.

Нужно вот так сконфигурировать контейнер (если версия Yii2 свежая - вроде бы от 2.0.9 идет):

```
'pistol88\order\interfaces\Cart' => [
                'class' => 'pistol88\order\drivers\Pistol88Cart'
            ],
            'pistol88\order\interfaces\OrderElement' => [
                'class' => 'pistol88\order\models\Element'
            ]
```

Если старая, то как в ридми, через контейнер.
```
yii::$container->set('pistol88\order\interfaces\Cart', 'pistol88\order\drivers\Pistol88Cart');
yii::$container->set('pistol88\order\interfaces\OrderElement', 'pistol88\order\models\Element');
```

Суть во второй замене интерфейса, иначе будет ругань:
**Can not instantiate pistol88\order\interfaces\OrderElement.**

**Comment by pistol88** [comment]
OrderElement инжекстится в Bootstrap.php https://github.com/pistol88/yii2-order/blob/master/Bootstrap.php

У вас он не подключается при установке?

**Comment by TheElk** [comment]
А, точно - не заметил. Я использую, как модуль:
http://yiiframework.ru/forum/viewtopic.php?f=19&t=43148

Тогда в конфиге:

bootstrap => [
'pistol88\order\Bootstrap'
]

**Comment by pistol88** [comment]
> Так?

Да, как-то так.

**Comment by TheElk** [comment]
Спасибо :)
Не знаю, наверно, не нужно в readme добавлять, кому надо - знают..

**Comment by pistol88** [comment]
Когда заработает - сделайте ПР, пожалуйста, с описанием того, как устанавливать не через Компосер :)

**Comment by TheElk** [comment]
Добро, вечером будет время, сделаю.
