### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ApXaHgheJI** [pistol88/yii2-order#4]
exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: pistol88\order\Module::cartService' in /vendor/yiisoft/yii2/base/Component.php:197
Stack trace:

Его просто нет в модуле.
По этому или убрать его из докухи или добавить - ток хз зачем он там )

minusAmount - тоже самое не понятная функция... ( может из имени конечно и можно чет там понять - но зачем она \ и где она ... хз )

Просто создал ее пустой - пусть будет - не важно мне сейчас...

**Comment by pistol88** [comment]
cartService убрал с ридми, спасибо!

minusAmout и plusAmount - это эксперименты с потенциальной ERP (для ведения остатков). Вскоре эти методы переберутся в отдельный механизм (списание со скада).
