### ISSUE TITLE
plusAmount - доже бы пока его убрать

### ISSUE THREAD

**Issue by ApXaHgheJI** [pistol88/yii2-order#5]
Calling unknown method: backend\modules\store\models\Products::plusAmount()

**Comment by ApXaHgheJI** [comment]
А так же хотел бы спросить - у тебя запрос делает вывод заказов в админке исходя если есть узер.
так вот - у меня допустим в магазе узеров не будет - просто заказ идет.
но в этом случай seller_user_id - NULL , как обойти траблу ?

ПСЫ: немного не понимаю зачем он тут ваше ? Seller - продавец ... так как должен быть ID в админке ? в чем была задумка ?

**Comment by pistol88** [comment]
Модель, которая может быть заказана, должна имплементировать pistol88/order/interfaces/Product.
Убирать пока что нет возможности, потому что нет видения, куда убирать (склады только в разработке).

Продавец (seller_id) нужен, чтобы кассир (он же и продавец) видел только свои заказы (то есть только те заказы, которые провел он (там в модуле еще вшито АРМ для добавления заказа в офлайн точке). Завтра сделаю эту фильтрацию не по умолчанию.

**Comment by pistol88** [comment]
Система пилится для стартапа "онлайн и офлайн точка в одной админке", поэтому там есть странности пока что))

**Comment by ApXaHgheJI** [comment]
> Система пилится для стартапа "онлайн и офлайн точка в одной админке", поэтому там есть странности пока что))

П.С. было бы удобно кстати добавить конвертер валюты - ну может сам потом чет допилю - магазин пока убрал в сторону - оставлю только корзину из модулей... свою напишу )

**Comment by pistol88** [comment]
Угу, валюты и локализации еще не покрыты. Будем рады, если пулл реквест какой сделаешь в какой из модулей, удачи :+1:
